name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@vc
    - name: docker login
      env: 
        DOCKERJJSER: ${{sec rets.DOCKER.USER}}
        DOCKER.PASSWORD: ${{secrets.DOCKER_PASSWORD}>
      run: docker build . —file Dockerfile —tag chamodshehanka/node- test:$(date +%s)
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER»/filedrop
